# Part 1: Data Loading and Analysis

## 1. Data Loading

### 1.1 Load Data from ArcGIS

In [5]:
import requests

url = "https://maps.ottawa.ca/arcgis/rest/services/WaterandWastewaterInfrastructure/MapServer/8/query"

pipes = []

offset = 0
batch_size = 1000

while True:
    params = {
        "where": "1=1",
        "outFields": "*",
        "returnGeometry": "true",
        "resultOffset": offset,
        "resultRecordCount": batch_size,
        "f": "json"
    }

    data = requests.get(url, params=params).json()

    features = data.get("features", [])

    if len(features) == 0:
        break
    pipes.extend(features)


    offset += batch_size
pipes

[{'attributes': {'OBJECTID': 3,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN10007',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1992,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 112.4800033569336,
   'INVERT_DOWNSTREAM': 111.45999908447266,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 88.8275959939448,
   'ENABLED': 1,
   'GLOBALID': '{42FA8C85-5F59-45AA-873B-7552758F582D}',
   'LENGTHASBUILT': 62.7},
  'geometry': {'paths': [[[-8463015.0737, 5676545.834600002],
     [-8462955.2619, 5676480.1620000005]]]}},
 {'attributes': {'OBJECTID': 4,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN12058',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1990,
   'WIDTH': 300,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 95.7300033569336,
   'INVERT_DOWNSTREAM': 95.6500015258789,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 37.238052588438,
   'ENABLED': 1,
   'GLOBALID': '{3A14750B-4AFF-4E5E-B75B-3C2E804D45AF}',
   'LENGTHASBUILT': 26},
  'geometry': {'paths': [[[-8450682.9022, 5672343.8532000035],
     [-8450704.201, 5672374.398800001]]]}},
 {'attributes': {'OBJECTID': 5,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN21525',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1986,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 82.4219970703125,
   'INVERT_DOWNSTREAM': 82.33599853515625,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 30.847636566131403,
   'ENABLED': 1,
   'GLOBALID': '{B085289C-887E-4632-AE88-E409CEA479A8}',
   'LENGTHASBUILT': 20.900000000000002},
  'geometry': {'paths': [[[-8408925.9903, 5692079.231799997],
     [-8408955.1469, 5692069.1586000025]]]}},
 {'attributes': {'OBJECTID': 6,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN21574',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1985,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 82.65899658203125,
   'INVERT_DOWNSTREAM': 82.35800170898438,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 125.41075333896941,
   'ENABLED': 1,
   'GLOBALID': '{A5769DE4-F6FB-452B-9B80-DE00D308B704}',
   'LENGTHASBUILT': 88.2},
  'geometry': {'paths': [[[-8409038.9094, 5691434.7973000035],
     [-8409098.1821, 5691545.317000002]]]}},
 {'attributes': {'OBJECTID': 7,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN00464',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1983,
   'WIDTH': 900,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 64.7300033569336,
   'INVERT_DOWNSTREAM': 63.803001403808594,
   'FUNCTION': 'COLLECTOR',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 120.91162475727978,
   'ENABLED': 1,
   'GLOBALID': '{33EAE45F-3C82-4090-8200-22AA29B195D7}',
   'LENGTHASBUILT': 85},
  'geometry': {'paths': [[[-8410044.2021, 5694130.608400002],
     [-8410049.2, 5694174.747000001],
     [-8410057.8077, 5694250.752099998]]]}},
 {'attributes': {'OBJECTID': 15,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN49404',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 2005,
   'WIDTH': 200,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 90.5999984741211,
   'INVERT_DOWNSTREAM': 89.81500244140625,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 104.09720777106726,
   'ENABLED': 1,
   'GLOBALID': '{0109381B-6C45-4A10-968A-90AF2D86EEA7}',
   'LENGTHASBUILT': 72.9},
  'geometry': {'paths': [[[-8415684.7625, 5671454.0075],
     [-8415645.7644, 5671357.491300002]]]}},
 {'attributes': {'OBJECTID': 17,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN49415',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PRIVATE',
   'INSTALL_YEAR': 0,
   'WIDTH': 0,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 0,
   'INVERT_DOWNSTREAM': 0,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 16.450624858969878,
   'ENABLED': 1,
   'GLOBALID': '{8963CAB1-E9F7-45FF-9AD9-35F2EAA5475D}',
   'LENGTHASBUILT': 0},
  'geometry': {'paths': [[[-8427948.0973, 5676449.8662],
     [-8427962.0799, 5676441.199600004]]]}},
 {'attributes': {'OBJECTID': 19,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN39274',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1934,
   'WIDTH': 250,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 52.900001525878906,
   'INVERT_DOWNSTREAM': 52.85100173950195,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 18.24215288644484,
   'ENABLED': 1,
   'GLOBALID': '{FBE46BB4-FC1C-4485-B1BE-96BC95E9DF4A}',
   'LENGTHASBUILT': 12.5},
  'geometry': {'paths': [[[-8425901.7244, 5691488.5013],
     [-8425909.0551, 5691471.796899997]]]}},
 {'attributes': {'OBJECTID': 22,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN47346',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PRIVATE',
   'INSTALL_YEAR': 0,
   'WIDTH': 600,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 64.94999694824219,
   'INVERT_DOWNSTREAM': 64.62000274658203,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 95.88242277952676,
   'ENABLED': 1,
   'GLOBALID': '{601B585B-8085-4F29-B0B5-4FE403DC14B3}',
   'LENGTHASBUILT': 67},
  'geometry': {'paths': [[[-8424827.8925, 5688235.056500003],
     [-8424779.2426, 5688152.4331]]]}},
 {'attributes': {'OBJECTID': 25,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN37071',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1974,
   'WIDTH': 300,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 64.81600189208984,
   'INVERT_DOWNSTREAM': 64.48600006103516,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 125.28074295022977,
   'ENABLED': 1,
   'GLOBALID': '{ECF300B5-425A-4A58-A21D-A508567F188A}',
   'LENGTHASBUILT': 87.2},
  'geometry': {'paths': [[[-8429551.8842, 5684955.492799997],
     [-8429600.0181, 5685071.157799996]]]}},
 {'attributes': {'OBJECTID': 26,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN32943',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1956,
   'WIDTH': 300,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 94.68900299072266,
   'INVERT_DOWNSTREAM': 94.36299896240234,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 103.37056678075854,
   'ENABLED': 1,
   'GLOBALID': '{5E85B581-135A-4B5D-B2BA-78341F357DBE}',
   'LENGTHASBUILT': 85.3},
  'geometry': {'paths': [[[-8422583.6927, 5681493.5178999975],
     [-8422566.2243, 5681391.634000003]]]}},
 {'attributes': {'OBJECTID': 29,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN20046',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1998,
   'WIDTH': 375,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 90.54000091552734,
   'INVERT_DOWNSTREAM': 90.38999938964844,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 70.7134605716712,
   'ENABLED': 1,
   'GLOBALID': '{7E6C456B-122C-442E-BA96-E39BB4440577}',
   'LENGTHASBUILT': 50},
  'geometry': {'paths': [[[-8429365.7822, 5665231.279799998],
     [-8429301.7827, 5665261.354000002]]]}},
 {'attributes': {'OBJECTID': 30,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN14931',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1973,
   'WIDTH': 375,
   'MATERIAL': 'AC',
   'INVERT_UPSTREAM': 84.87000274658203,
   'INVERT_DOWNSTREAM': 84.55000305175781,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 62.61194094583933,
   'ENABLED': 1,
   'GLOBALID': '{374CC7C5-9886-4DF2-9F60-BDE7E18C2F86}',
   'LENGTHASBUILT': 42},
  'geometry': {'paths': [[[-8434937.1164, 5673559.087800004],
     [-8434946.0523, 5673621.058799997]]]}},
 {'attributes': {'OBJECTID': 31,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN39681',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1997,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 67.1500015258789,
   'INVERT_DOWNSTREAM': 66.80000305175781,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 121.95773233223098,
   'ENABLED': 1,
   'GLOBALID': '{F747C23F-BD27-4847-B07C-571ABA4EBA69}',
   'LENGTHASBUILT': 87.5},
  'geometry': {'paths': [[[-8424042.7238, 5689292.223700002],
     [-8424099.9265, 5689256.9043999985],
     [-8424146.6903, 5689228.470399998]]]}},
 {'attributes': {'OBJECTID': 37,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN26812',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1956,
   'WIDTH': 225,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 77.53800201416016,
   'INVERT_DOWNSTREAM': 76.5780029296875,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 92.56385698122423,
   'ENABLED': 1,
   'GLOBALID': '{F955D8A8-1F3D-4B4E-B9A2-EBB6F99B3EDB}',
   'LENGTHASBUILT': 64.1},
  'geometry': {'paths': [[[-8433886.6142, 5678105.116400003],
     [-8433972.3239, 5678070.160499997]]]}},
 {'attributes': {'OBJECTID': 41,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN26818',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1956,
   'WIDTH': 225,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 79.32099914550781,
   'INVERT_DOWNSTREAM': 77.8759994506836,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 78.20652208462074,
   'ENABLED': 1,
   'GLOBALID': '{D02749C8-2351-4B4A-A3B2-63F88D65C118}',
   'LENGTHASBUILT': 54.800000000000004},
  'geometry': {'paths': [[[-8433866.7846, 5677673.8510000035],
     [-8433897.3206, 5677745.849699996]]]}},
 {'attributes': {'OBJECTID': 42,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN28007',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1952,
   'WIDTH': 1200,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 52.5099983215332,
   'INVERT_DOWNSTREAM': 52.27000045776367,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 232.39028802948636,
   'ENABLED': 1,
   'GLOBALID': '{1C36C2D1-DBE3-4B75-A0FC-37E811AF4D2D}',
   'LENGTHASBUILT': 163.70000000000002},
  'geometry': {'paths': [[[-8431912.3219, 5684868.0251],
     [-8431826.1365, 5684652.2073]]]}},
 {'attributes': {'OBJECTID': 43,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN28015',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 0,
   'WIDTH': 450,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 54.84000015258789,
   'INVERT_DOWNSTREAM': 54.18000030517578,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 103.39777322603015,
   'ENABLED': 1,
   'GLOBALID': '{9371EAA3-CA90-42D6-9D84-DA2D3E805F1B}',
   'LENGTHASBUILT': 72.8},
  'geometry': {'paths': [[[-8431945.7774, 5685606.223499998],
     [-8432041.8542, 5685568.009000003]]]}},
 {'attributes': {'OBJECTID': 46,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN23581',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1968,
   'WIDTH': 450,
   'MATERIAL': 'CONR',
   'INVERT_UPSTREAM': 72.26000213623047,
   'INVERT_DOWNSTREAM': 71.98100280761719,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 129.35023119039676,
   'ENABLED': 1,
   'GLOBALID': '{6A1E93A5-2892-4399-864D-D0DEA712A903}',
   'LENGTHASBUILT': 92.4},
  'geometry': {'paths': [[[-8416122.4105, 5690696.161899999],
     [-8416011.7019, 5690763.057999998]]]}},
 {'attributes': {'OBJECTID': 53,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN26813',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1956,
   'WIDTH': 225,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 77.76699829101562,
   'INVERT_DOWNSTREAM': 77.53800201416016,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 90.29645369047803,
   'ENABLED': 1,
   'GLOBALID': '{6045D335-7990-48FA-9EE0-1AD52CB9FC6A}',
   'LENGTHASBUILT': 64.6},
  'geometry': {'paths': [[[-8433802.3981, 5678137.690899998],
     [-8433886.6142, 5678105.116400003]]]}},
 {'attributes': {'OBJECTID': 54,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN26808',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1956,
   'WIDTH': 225,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 78.30000305175781,
   'INVERT_DOWNSTREAM': 78.54399871826172,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 72.58242607377439,
   'ENABLED': 1,
   'GLOBALID': '{4FCF1476-BE25-40DD-B9D2-9517429DBDC5}',
   'LENGTHASBUILT': 50.4},
  'geometry': {'paths': [[[-8433869.7712, 5677557.046599999],
     [-8433941.9774, 5677549.666000001]]]}},
 {'attributes': {'OBJECTID': 56,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN26375',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 0,
   'WIDTH': 225,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 82.697998046875,
   'INVERT_DOWNSTREAM': 82.40599822998047,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 121.13723179192536,
   'ENABLED': 1,
   'GLOBALID': '{1BFEA17F-F132-4916-ACB4-8D1C5DE71822}',
   'LENGTHASBUILT': 85.10000000000001},
  'geometry': {'paths': [[[-8433618.6063, 5679976.807899997],
     [-8433574.649, 5679863.927500002]]]}},
 {'attributes': {'OBJECTID': 58,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN26374',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 0,
   'WIDTH': 225,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 82.40599822998047,
   'INVERT_DOWNSTREAM': 82.10700225830078,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 104.95315696475839,
   'ENABLED': 1,
   'GLOBALID': '{BCFC7FEB-AD1F-420C-BFD8-5DFFAAA37FAC}',
   'LENGTHASBUILT': 73.7},
  'geometry': {'paths': [[[-8433574.649, 5679863.927500002],
     [-8433535.8985, 5679766.390000001]]]}},
 {'attributes': {'OBJECTID': 59,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN24729',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 2002,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 96.26000213623047,
   'INVERT_DOWNSTREAM': 95.95999908447266,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 64.42003969308662,
   'ENABLED': 1,
   'GLOBALID': '{3A703C73-39BD-494D-9E58-5D929A01E726}',
   'LENGTHASBUILT': 45.5},
  'geometry': {'paths': [[[-8431874.3355, 5664205.990800001],
     [-8431905.6254, 5664262.301399998]]]}},
 {'attributes': {'OBJECTID': 60,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN49559',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 2007,
   'WIDTH': 200,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 94.44000244140625,
   'INVERT_DOWNSTREAM': 94.0199966430664,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 37.350295320257075,
   'ENABLED': 1,
   'GLOBALID': '{239325B6-0201-4E8C-88E3-9E5497B8A8F6}',
   'LENGTHASBUILT': 27.5},
  'geometry': {'paths': [[[-8429589.9613, 5660415.200599998],
     [-8429571.9862, 5660447.941100001]]]}},
 {'attributes': {'OBJECTID': 61,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN23132',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1968,
   'WIDTH': 300,
   'MATERIAL': 'CONR',
   'INVERT_UPSTREAM': 61.189998626708984,
   'INVERT_DOWNSTREAM': 60.91999816894531,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 128.7444164577583,
   'ENABLED': 1,
   'GLOBALID': '{0379B8F2-7C5B-4F4D-9E99-11EF245DC78F}',
   'LENGTHASBUILT': 90.3},
  'geometry': {'paths': [[[-8417048.8655, 5687503.750200003],
     [-8417008.9565, 5687381.347599998]]]}},
 {'attributes': {'OBJECTID': 62,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN48005',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 2004,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 81.83000183105469,
   'INVERT_DOWNSTREAM': 81.55000305175781,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 98.75269405341577,
   'ENABLED': 1,
   'GLOBALID': '{E823932B-B70B-4F1F-BD99-45C3F5D805C7}',
   'LENGTHASBUILT': 69},
  'geometry': {'paths': [[[-8426662.804, 5678377.865400001],
     [-8426652.1343, 5678279.690800004]]]}},
 {'attributes': {'OBJECTID': 64,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN49172',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 2005,
   'WIDTH': 200,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 108.39800262451172,
   'INVERT_DOWNSTREAM': 107.80699920654297,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 58.16015387725898,
   'ENABLED': 1,
   'GLOBALID': '{7A0958F8-E343-4C92-A829-78FA43D33637}',
   'LENGTHASBUILT': 40.7},
  'geometry': {'paths': [[[-8444452.1214, 5666675.853699997],
     [-8444429.0703, 5666622.456600003]]]}},
 {'attributes': {'OBJECTID': 67,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN49412',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 2006,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 79.04000091552734,
   'INVERT_DOWNSTREAM': 78.8499984741211,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 87.02593743502112,
   'ENABLED': 1,
   'GLOBALID': '{6EC25582-4C66-4925-A5FB-591D54219349}',
   'LENGTHASBUILT': 61.4},
  'geometry': {'paths': [[[-8427824.7074, 5676510.930600002],
     [-8427737.7212, 5676513.560199998]]]}},
 {'attributes': {'OBJECTID': 70,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN17211',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1988,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 84.60399627685547,
   'INVERT_DOWNSTREAM': 84.40499877929688,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 99.3250895147776,
   'ENABLED': 1,
   'GLOBALID': '{32E7C9BB-35B1-4EFD-B39F-9886EDAD68C7}',
   'LENGTHASBUILT': 70.2},
  'geometry': {'paths': [[[-8429543.3435, 5674997.315899998],
     [-8429640.863, 5674978.463299997]]]}},
 {'attributes': {'OBJECTID': 71,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN34060',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1962,
   'WIDTH': 375,
   'MATERIAL': 'CONC',
   'INVERT_UPSTREAM': 77.43699645996094,
   'INVERT_DOWNSTREAM': 77.2239990234375,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 77.81903041657179,
   'ENABLED': 1,
   'GLOBALID': '{F5C85574-A9A4-483A-B7AC-D9D1CDDBCEB8}',
   'LENGTHASBUILT': 92},
  'geometry': {'paths': [[[-8423747.2223, 5679670.144900002],
     [-8423752.0522, 5679747.813900001]]]}},
 {'attributes': {'OBJECTID': 72,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN06074',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1971,
   'WIDTH': 250,
   'MATERIAL': 'AC',
   'INVERT_UPSTREAM': 90.47000122070312,
   'INVERT_DOWNSTREAM': 90.12000274658203,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 129.63424157376244,
   'ENABLED': 1,
   'GLOBALID': '{8D2518E3-EA45-4139-9198-B8D5184B2EEA}',
   'LENGTHASBUILT': 91.7},
  'geometry': {'paths': [[[-8442039.729, 5651981.831900001],
     [-8441953.0482, 5651885.439599998]]]}},
 {'attributes': {'OBJECTID': 73,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN10009',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 1992,
   'WIDTH': 250,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 111.22000122070312,
   'INVERT_DOWNSTREAM': 107.37999725341797,
   'FUNCTION': None,
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 153.1216231072762,
   'ENABLED': 1,
   'GLOBALID': '{95C42B86-6BAA-430E-8580-6C7ABFC38CEB}',
   'LENGTHASBUILT': 107.5},
  'geometry': {'paths': [[[-8462955.1874, 5676463.413999997],
     [-8462992.6206, 5676420.812299997],
     [-8463028.0296, 5676380.146499999],
     [-8463056.2754, 5676348.405199997]]]}},
 {'attributes': {'OBJECTID': 74,
   'SUBTYPE': 1,
   'STRUCT_ID': 'SAN50259',
   'STRUCT_TYPE': 'SANP',
   'OWNERSHIP': 'PUBLIC',
   'INSTALL_YEAR': 2006,
   'WIDTH': 200,
   'MATERIAL': 'PVC',
   'INVERT_UPSTREAM': 96.78700256347656,
   'INVERT_DOWNSTREAM': 94.9800033569336,
   'FUNCTION': 'LOCAL',
   'LIFE_CYCLE_STATUS': 'IN_SERVICE',
   'SHAPE_Length': 82.31564178306598,
   'ENABLED': 1,
   'GLOBALID': '{8B3F3450-8ABD-4149-AECC-B64300B18026}',
   'LENGTHASBUILT': 58.300000000000004},
  'geometry': {'paths': [[[-8453526.0514, 5675790.012400001],

### 1.2 Export Raw Data

In [8]:
import json
with open("data/pipes_raw.json", "w") as file:
    json.dump(pipes, file, indent=4)

### 1.3 Make Data into a Table

In [10]:
import pandas as pd
pipes_a = pd.DataFrame([object["attributes"] for object in pipes])
pipes_gx1 = pd.DataFrame([object["geometry"]["paths"][0][0][0] for object in pipes], columns=["x1"])
pipes_gy1 = pd.DataFrame([object["geometry"]["paths"][0][0][1] for object in pipes], columns=["y1"])
pipes_gx2 = pd.DataFrame([object["geometry"]["paths"][0][1][0] for object in pipes], columns=["x2"])
pipes_gy2 = pd.DataFrame([object["geometry"]["paths"][0][1][1] for object in pipes], columns=["y2"])

In [11]:
pipes = pd.concat([pipes_a, pipes_gx1, pipes_gy1, pipes_gx2, pipes_gy2], axis=1)
pipes

,OBJECTID,SUBTYPE,STRUCT_ID,STRUCT_TYPE,OWNERSHIP,INSTALL_YEAR,WIDTH,MATERIAL,INVERT_UPSTREAM,INVERT_DOWNSTREAM,FUNCTION,LIFE_CYCLE_STATUS,SHAPE_Length,ENABLED,GLOBALID,LENGTHASBUILT,x1,y1,x2,y2
0,3,1,SAN10007,SANP,PUBLIC,1992.0,250.0,PVC,112.480003,111.459999,NaN,IN_SERVICE,88.827596,1,{42FA8C85-5F59-45AA-873B-7552758F582D},62.7,-8.463015e+06,5.676546e+06,-8.462955e+06,5.676480e+06
1,4,1,SAN12058,SANP,PUBLIC,1990.0,300.0,PVC,95.730003,95.650002,NaN,IN_SERVICE,37.238053,1,{3A14750B-4AFF-4E5E-B75B-3C2E804D45AF},26.0,-8.450683e+06,5.672344e+06,-8.450704e+06,5.672374e+06
2,5,1,SAN21525,SANP,PUBLIC,1986.0,250.0,PVC,82.421997,82.335999,NaN,IN_SERVICE,30.847637,1,{B085289C-887E-4632-AE88-E409CEA479A8},20.9,-8.408926e+06,5.692079e+06,-8.408955e+06,5.692069e+06
3,6,1,SAN21574,SANP,PUBLIC,1985.0,250.0,PVC,82.658997,82.358002,NaN,IN_SERVICE,125.410753,1,{A5769DE4-F6FB-452B-9B80-DE00D308B704},88.2,-8.409039e+06,5.691435e+06,-8.409098e+06,5.691545e+06
4,7,1,SAN00464,SANP,PUBLIC,1983.0,900.0,CONC,64.730003,63.803001,COLLECTOR,IN_SERVICE,120.911625,1,{33EAE45F-3C82-4090-8200-22AA29B195D7},85.0,-8.410044e+06,5.694131e+06,-8.410049e+06,5.694175e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61334,1043775,1,SAN91525,SANP,PUBLIC,2026.0,200.0,PVC,87.209999,87.160004,LOCAL,IN_SERVICE,21.689989,1,{A68C36C8-9C33-46B1-994D-9B254EBF014D},15.2,-8.425582e+06,5.655315e+06,-8.425563e+06,5.655305e+06
61335,1043776,1,SAN91529,SANP,PUBLIC,2026.0,200.0,PVC,87.360001,87.010002,LOCAL,IN_SERVICE,125.600289,1,{AC78EE14-B12B-484F-9753-44683EA9DA8D},88.4,-8.425378e+06,5.655430e+06,-8.425439e+06,5.655540e+06
61336,1043777,1,SAN91532,SANP,PUBLIC,2026.0,200.0,PVC,87.199997,86.970001,LOCAL,IN_SERVICE,79.948886,1,{CBA27F2B-98A9-49F2-BDFD-22A1DD53AD3B},56.3,-8.425561e+06,5.655347e+06,-8.425491e+06,5.655387e+06
61337,1043778,1,SAN91527,SANP,PUBLIC,2026.0,200.0,PVC,87.559998,87.430000,LOCAL,IN_SERVICE,47.848218,1,{E4E856F5-6007-41F9-926D-F0ACC647F449},33.6,-8.425680e+06,5.655366e+06,-8.425640e+06,5.655340e+06
61338,1043779,1,SAN91524,SANP,PUBLIC,2026.0,200.0,PVC,87.129997,87.010002,LOCAL,IN_SERVICE,44.276536,1,{F75CFE7A-9236-438A-A6FC-6050CDE259E7},31.2,-8.425563e+06,5.655305e+06,-8.425539e+06,5.655267e+06

### 1.4 Export Tabular Data

In [ ]:
pipes.to_csv("data/pipes_tabular.csv", index=False)

## 2. Basic Data Cleaning

In [12]:
pipes.info()

<class 'pandas.DataFrame'>
RangeIndex: 61339 entries, 0 to 61338
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OBJECTID           61339 non-null  int64
 1   SUBTYPE            61339 non-null  int64
 2   STRUCT_ID          61339 non-null  str
 3   STRUCT_TYPE        61339 non-null  str
 4   OWNERSHIP          61339 non-null  str
 5   INSTALL_YEAR       61257 non-null  float64
 6   WIDTH              61285 non-null  float64
 7   MATERIAL           61334 non-null  str
 8   INVERT_UPSTREAM    61248 non-null  float64
 9   INVERT_DOWNSTREAM  61261 non-null  float64
 10  FUNCTION           35470 non-null  str
 11  LIFE_CYCLE_STATUS  61339 non-null  str
 12  SHAPE_Length       61339 non-null  float64
 13  ENABLED            61339 non-null  int64
 14  GLOBALID           61339 non-null  str
 15  LENGTHASBUILT      60282 non-null  float64
 16  x1                 61339 non-null  float64
 17  y1                 61339 non-null  float64
 18  x2                 61339 non-null  float64
 19  y2                 61339 non-null  float64
dtypes: float64(10), int64(3), str(7)
memory usage: 9.4 MB

The following columns will be removed
- OBJECTID, SUBTYPE, STRUCT_ID, GLOBAL_ID, SHAPE_Length are unhelpful features
- STRUCT_TYPE and LIFECYCLE_STATUS all consist of only one unique value
- ENABLED is all 1 except 1 sample
- 42% of FUNCTION are NaN

In [29]:
pipes_cleaned = pipes.drop(["OBJECTID", "SUBTYPE", "STRUCT_ID", "GLOBALID", "STRUCT_TYPE", "LIFE_CYCLE_STATUS", "ENABLED", "FUNCTION", "SHAPE_Length"], axis=1)
pipes_cleaned

,OWNERSHIP,INSTALL_YEAR,WIDTH,MATERIAL,INVERT_UPSTREAM,INVERT_DOWNSTREAM,LENGTHASBUILT,x1,y1,x2,y2
0,PUBLIC,1992.0,250.0,PVC,112.480003,111.459999,62.7,-8.463015e+06,5.676546e+06,-8.462955e+06,5.676480e+06
1,PUBLIC,1990.0,300.0,PVC,95.730003,95.650002,26.0,-8.450683e+06,5.672344e+06,-8.450704e+06,5.672374e+06
2,PUBLIC,1986.0,250.0,PVC,82.421997,82.335999,20.9,-8.408926e+06,5.692079e+06,-8.408955e+06,5.692069e+06
3,PUBLIC,1985.0,250.0,PVC,82.658997,82.358002,88.2,-8.409039e+06,5.691435e+06,-8.409098e+06,5.691545e+06
4,PUBLIC,1983.0,900.0,CONC,64.730003,63.803001,85.0,-8.410044e+06,5.694131e+06,-8.410049e+06,5.694175e+06
...,...,...,...,...,...,...,...,...,...,...,...
61334,PUBLIC,2026.0,200.0,PVC,87.209999,87.160004,15.2,-8.425582e+06,5.655315e+06,-8.425563e+06,5.655305e+06
61335,PUBLIC,2026.0,200.0,PVC,87.360001,87.010002,88.4,-8.425378e+06,5.655430e+06,-8.425439e+06,5.655540e+06
61336,PUBLIC,2026.0,200.0,PVC,87.199997,86.970001,56.3,-8.425561e+06,5.655347e+06,-8.425491e+06,5.655387e+06
61337,PUBLIC,2026.0,200.0,PVC,87.559998,87.430000,33.6,-8.425680e+06,5.655366e+06,-8.425640e+06,5.655340e+06
61338,PUBLIC,2026.0,200.0,PVC,87.129997,87.010002,31.2,-8.425563e+06,5.655305e+06,-8.425539e+06,5.655267e+06

In [30]:
pipes_cleaned = pipes_cleaned.dropna()
pipes_cleaned

,OWNERSHIP,INSTALL_YEAR,WIDTH,MATERIAL,INVERT_UPSTREAM,INVERT_DOWNSTREAM,LENGTHASBUILT,x1,y1,x2,y2
0,PUBLIC,1992.0,250.0,PVC,112.480003,111.459999,62.7,-8.463015e+06,5.676546e+06,-8.462955e+06,5.676480e+06
1,PUBLIC,1990.0,300.0,PVC,95.730003,95.650002,26.0,-8.450683e+06,5.672344e+06,-8.450704e+06,5.672374e+06
2,PUBLIC,1986.0,250.0,PVC,82.421997,82.335999,20.9,-8.408926e+06,5.692079e+06,-8.408955e+06,5.692069e+06
3,PUBLIC,1985.0,250.0,PVC,82.658997,82.358002,88.2,-8.409039e+06,5.691435e+06,-8.409098e+06,5.691545e+06
4,PUBLIC,1983.0,900.0,CONC,64.730003,63.803001,85.0,-8.410044e+06,5.694131e+06,-8.410049e+06,5.694175e+06
...,...,...,...,...,...,...,...,...,...,...,...
61334,PUBLIC,2026.0,200.0,PVC,87.209999,87.160004,15.2,-8.425582e+06,5.655315e+06,-8.425563e+06,5.655305e+06
61335,PUBLIC,2026.0,200.0,PVC,87.360001,87.010002,88.4,-8.425378e+06,5.655430e+06,-8.425439e+06,5.655540e+06
61336,PUBLIC,2026.0,200.0,PVC,87.199997,86.970001,56.3,-8.425561e+06,5.655347e+06,-8.425491e+06,5.655387e+06
61337,PUBLIC,2026.0,200.0,PVC,87.559998,87.430000,33.6,-8.425680e+06,5.655366e+06,-8.425640e+06,5.655340e+06
61338,PUBLIC,2026.0,200.0,PVC,87.129997,87.010002,31.2,-8.425563e+06,5.655305e+06,-8.425539e+06,5.655267e+06

In [32]:
import numpy as np

cols_to_check = ["INSTALL_YEAR", "WIDTH", "LENGTHASBUILT", "x1", "y1", "x2", "y2"]
pipes_cleaned[cols_to_check] = pipes_cleaned[cols_to_check].replace(0.0, np.nan)

In [33]:
pipes_cleaned = pipes_cleaned.dropna()

In [34]:
pipes_cleaned

,OWNERSHIP,INSTALL_YEAR,WIDTH,MATERIAL,INVERT_UPSTREAM,INVERT_DOWNSTREAM,LENGTHASBUILT,x1,y1,x2,y2
0,PUBLIC,1992.0,250.0,PVC,112.480003,111.459999,62.7,-8.463015e+06,5.676546e+06,-8.462955e+06,5.676480e+06
1,PUBLIC,1990.0,300.0,PVC,95.730003,95.650002,26.0,-8.450683e+06,5.672344e+06,-8.450704e+06,5.672374e+06
2,PUBLIC,1986.0,250.0,PVC,82.421997,82.335999,20.9,-8.408926e+06,5.692079e+06,-8.408955e+06,5.692069e+06
3,PUBLIC,1985.0,250.0,PVC,82.658997,82.358002,88.2,-8.409039e+06,5.691435e+06,-8.409098e+06,5.691545e+06
4,PUBLIC,1983.0,900.0,CONC,64.730003,63.803001,85.0,-8.410044e+06,5.694131e+06,-8.410049e+06,5.694175e+06
...,...,...,...,...,...,...,...,...,...,...,...
61334,PUBLIC,2026.0,200.0,PVC,87.209999,87.160004,15.2,-8.425582e+06,5.655315e+06,-8.425563e+06,5.655305e+06
61335,PUBLIC,2026.0,200.0,PVC,87.360001,87.010002,88.4,-8.425378e+06,5.655430e+06,-8.425439e+06,5.655540e+06
61336,PUBLIC,2026.0,200.0,PVC,87.199997,86.970001,56.3,-8.425561e+06,5.655347e+06,-8.425491e+06,5.655387e+06
61337,PUBLIC,2026.0,200.0,PVC,87.559998,87.430000,33.6,-8.425680e+06,5.655366e+06,-8.425640e+06,5.655340e+06
61338,PUBLIC,2026.0,200.0,PVC,87.129997,87.010002,31.2,-8.425563e+06,5.655305e+06,-8.425539e+06,5.655267e+06

## 3. Creating Calculated Features
- AGE
- SLOPE

In [37]:
pipes_cleaned["AGE"] = 2026 - pipes_cleaned["INSTALL_YEAR"]
pipes_cleaned["SLOPE"] = (pipes_cleaned["INVERT_UPSTREAM"] - pipes_cleaned["INVERT_DOWNSTREAM"]) / pipes_cleaned["LENGTHASBUILT"]
pipes_cleaned

,OWNERSHIP,INSTALL_YEAR,WIDTH,MATERIAL,INVERT_UPSTREAM,INVERT_DOWNSTREAM,LENGTHASBUILT,x1,y1,x2,y2,AGE,SLOPE
0,PUBLIC,1992.0,250.0,PVC,112.480003,111.459999,62.7,-8.463015e+06,5.676546e+06,-8.462955e+06,5.676480e+06,34.0,0.016268
1,PUBLIC,1990.0,300.0,PVC,95.730003,95.650002,26.0,-8.450683e+06,5.672344e+06,-8.450704e+06,5.672374e+06,36.0,0.003077
2,PUBLIC,1986.0,250.0,PVC,82.421997,82.335999,20.9,-8.408926e+06,5.692079e+06,-8.408955e+06,5.692069e+06,40.0,0.004115
3,PUBLIC,1985.0,250.0,PVC,82.658997,82.358002,88.2,-8.409039e+06,5.691435e+06,-8.409098e+06,5.691545e+06,41.0,0.003413
4,PUBLIC,1983.0,900.0,CONC,64.730003,63.803001,85.0,-8.410044e+06,5.694131e+06,-8.410049e+06,5.694175e+06,43.0,0.010906
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61334,PUBLIC,2026.0,200.0,PVC,87.209999,87.160004,15.2,-8.425582e+06,5.655315e+06,-8.425563e+06,5.655305e+06,0.0,0.003289
61335,PUBLIC,2026.0,200.0,PVC,87.360001,87.010002,88.4,-8.425378e+06,5.655430e+06,-8.425439e+06,5.655540e+06,0.0,0.003959
61336,PUBLIC,2026.0,200.0,PVC,87.199997,86.970001,56.3,-8.425561e+06,5.655347e+06,-8.425491e+06,5.655387e+06,0.0,0.004085
61337,PUBLIC,2026.0,200.0,PVC,87.559998,87.430000,33.6,-8.425680e+06,5.655366e+06,-8.425640e+06,5.655340e+06,0.0,0.003869
61338,PUBLIC,2026.0,200.0,PVC,87.129997,87.010002,31.2,-8.425563e+06,5.655305e+06,-8.425539e+06,5.655267e+06,0.0,0.003846